version: '2'

services:
  transmission:
    image: cdrage/transmission
    volumes:
      - ./media:/var/lib/transmission-daemon/downloads
    ports:
      - "9091:9091"
    environment:
      - TRUSER=admin
      - TRPASSWD=admin
    restart: always

  couchpotato:
    image: cdrage/couchpotato
    volumes:
      - ./couchpotato_config:/root/.couchpotato
    ports:
      - "5050:5050"
    depends_on:
      - transmission
    restart: always

  plex:
    image: wernight/plex-media-server:latest
    ports:
      # for access to the Plex Media Server [required]
      - "32400:32400"
      # for access to the Plex DLNA Server
      - "1900:1900/udp"
      - "32469:32469"
      # for controlling Plex Home Theater via Plex Companion
      - "3005:3005"
      # for older Bonjour/Avahi network discovery
      - "5353:5353/udp"
      # for controlling Plex for Roku via Plex Companion
      - "8324:8324"
      # for current GDM network discovery
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - ./plex_config:/config
      - ./media:/media
    # Only required for the first run, you may disable this after
    network_mode: host
    restart: always
