version: '2'

services:
  prometheus:
    image: prom/prometheus
    volumes: 
      - "./prometheus_config.yml:/etc/prometheus/prometheus.yml"
      - "./alert.rules:/etc/prometheus/alert.rules"
      - "./prometheus_data:/prometheus"
    command:
      - "-config.file=/etc/prometheus/prometheus.yml"
      - '-alertmanager.url=http://alertmanager:9093'
      - "-storage.local.path=/prometheus"
      - "-storage.local.memory-chunks=51200"
      - "-storage.local.max-chunks-to-persist=51200"
      - "-storage.local.retention=672h"
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes: 
      - "./prometheus_alert_config.yml:/etc/alertmanager/config.yml"
      - "./prometheus_alert_data:/prometheus"
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - "-storage.path=/prometheus"

  grafana:
    image: grafana/grafana
    volumes:
      - "./grafana_data:/var/lib/grafana"
    ports:
      - "3000:3000"
    env_file:
      - env.grafana
    depends_on:
      - prometheus
