rule_files:
  - "alert.rules"

scrape_configs:

  # Scrape Prometheus itself every 5 seconds.
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  # Scrape the Node Exporter every 5 seconds.
  - job_name: 'node'
    scrape_interval: 15s
    static_configs:
      - targets: ['backup01.domain.com:9100', 'kvmssd01.domain.com:9100']

  - job_name: 'kvm'
    scrape_interval: 15s
    static_configs:
      - targets: ['backup01.domain.com:9337', 'kvmssd01.domain.com:9337']
